source 'https://rubygems.org'

ruby '2.2.3'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'rspec'
gem 'capybara'
gem 'sinatra'
gem 'rake'
gem 'database_cleaner'
gem 'launchy'
gem 'bcrypt'
gem 'dm-validations'
gem 'sinatra-flash'
gem 'rest-client'
gem 'json'
